### ISSUE TITLE
Method to transfer themes to Alacritty?

### ISSUE THREAD

**Issue by t56k** [atelierbram/Base2Tone#2]
Not sure on the process here (if any).

**Comment by atelierbram** [comment]
Thanks for the question.
If I was going to make a Base2Tone-alacritty repo, I would take the [config file for Alacritty](https://github.com/jwilm/alacritty/blob/master/alacritty.yml) and make it into a template for base16-builder. Just like has been done for other applications like [Hyper](https://github.com/atelierbram/Base2Tone-hyperterm/blob/master/db/templates/hyperterm/dark.ejs).
I will do this when I think this Alacritty terminal is useable, and then whenever I can find some time.

**Comment by atelierbram** [comment]
@cd-rum please checkout the new duotone [Base2Tone colorschemes for Alacritty](https://github.com/atelierbram/Base2Tone-alacritty) terminal. Can you let me know if they work for you (_one might have to edit some preferences in the config, like the value for font-family, which is a consequence of having the colors not separate from but in the same file as the rest of the config_).
